version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "backend pre_build started"
      - cd book-backend
      - chmod +x gradlew

  build:
    commands:
      - echo "backend build started"
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo "backend build completed"

artifacts:
  files:
    - book-backend/build/libs/*.jar