version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - cd book-backend
      - chmod +x gradlew
  build:
    commands:
      - ./gradlew test
      - ./gradlew bootJar
  post_build:
    commands:
      - cp $CODEBUILD_SRC_DIR/book-backend/build/libs/*.jar $CODEBUILD_SRC_DIR/book-backend.jar
      - echo "Build completed on $(date)" # trigger3
artifacts:
  files:
    - 'book-backend.jar'
    - 'appspec.yml'
    - 'deploy-scripts/**/*'
  discard-paths: no
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
